# Generated by Django 3.2.9 on 2021-11-16 16:17

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=40
                )),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    blank=True,
                    max_length=40
                )),
                ('value', models.DecimalField(
                    decimal_places=2,
                    max_digits=10
                )),
                ('date', models.DateField(
                    default=datetime.date.today
                )),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    blank=True,
                    max_length=40)
                 ),
                ('value', models.DecimalField(
                    decimal_places=2,
                    max_digits=10
                )),
                ('date', models.DateField(
                    default=datetime.date.today
                )),
                ('category', models.ForeignKey(
                    default='',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='budget.category'
                )),
            ],
        ),
    ]
